PLATFORM_INCLUDE_DIRECTORY	:= /devkit/sh4/target/usr/include
PLATFORM_INCLUDE_DIRECTORYS	:= $(PLATFORM_INCLUDE_DIRECTORYS) $(PLATFORM_INCLUDE_DIRECTORY)
PLATFORM_INCLUDE_DIRECTORYS	:= $(PLATFORM_INCLUDE_DIRECTORYS) $(PLATFORM_INCLUDE_DIRECTORY)/c++/4.2.1
PLATFORM_INCLUDE_DIRECTORYS	:= $(PLATFORM_INCLUDE_DIRECTORYS) $(PLATFORM_INCLUDE_DIRECTORY)/c++/4.2.1/sh4-linux

PLATFORM_LIBRARY_DIRECTORYS	:= /devkit/sh4/target/usr/lib
