PLATFORM_INCLUDE_DIRECTORYS	:= $(PLATFORM_INCLUDE_DIRECTORYS) $(PLATFORM_TOOL_DIRECTORY)/android-mips-ndk-r5b-linux/platforms/android-8/arch-mips/usr/include
PLATFORM_LIBRARY_DIRECTORYS	:= $(PLATFORM_TOOL_DIRECTORY)/android-mips-ndk-r5b-linux/platforms/android-8/arch-mips/usr/lib

PLATFORM_COMPILE_FLAGS		:= $(PLATFORM_COMPILE_FLAGS) -EL
PLATFORM_COMPILE_FLAGS		:= $(PLATFORM_COMPILE_FLAGS) -march=mips32
PLATFORM_COMPILE_FLAGS		:= $(PLATFORM_COMPILE_FLAGS) -mtune=mips32
PLATFORM_COMPILE_FLAGS		:= $(PLATFORM_COMPILE_FLAGS) -mips32
PLATFORM_COMPILE_FLAGS		:= $(PLATFORM_COMPILE_FLAGS) -mhard-float
PLATFORM_COMPILE_FLAGS		:= $(PLATFORM_COMPILE_FLAGS) -ffunction-sections
PLATFORM_COMPILE_FLAGS		:= $(PLATFORM_COMPILE_FLAGS) -funwind-tables
PLATFORM_COMPILE_FLAGS		:= $(PLATFORM_COMPILE_FLAGS) -fno-short-enums 
PLATFORM_COMPILE_FLAGS		:= $(PLATFORM_COMPILE_FLAGS) -Wa,--noexecstack
PLATFORM_COMPILE_FLAGS		:= $(PLATFORM_COMPILE_FLAGS) -Wno-strict-aliasing
PLATFORM_COMPILE_FLAGS		:= $(PLATFORM_COMPILE_FLAGS) -DANDROID 

PLATFORM_COMPILE_FLAGS		:= $(PLATFORM_COMPILE_FLAGS) -D__ANDROID__=1

PLATFORM_LINK_FLAGS		:= $(PLATFORM_LINK_FLAGS) -EL
PLATFORM_LINK_FLAGS		:= $(PLATFORM_LINK_FLAGS) -march=mips32
PLATFORM_LINK_FLAGS		:= $(PLATFORM_LINK_FLAGS) -mtune=mips32
PLATFORM_LINK_FLAGS		:= $(PLATFORM_LINK_FLAGS) -mips32
PLATFORM_LINK_FLAGS		:= $(PLATFORM_LINK_FLAGS) -mhard-float
PLATFORM_LINK_FLAGS		:= $(PLATFORM_LINK_FLAGS) -nostdlib
PLATFORM_LINK_FLAGS		:= $(PLATFORM_LINK_FLAGS) -Bdynamic
PLATFORM_LINK_FLAGS		:= $(PLATFORM_LINK_FLAGS) -Wl,-dynamic-linker,/system/bin/linker
PLATFORM_LINK_FLAGS		:= $(PLATFORM_LINK_FLAGS) -Wl,--gc-sections
PLATFORM_LINK_FLAGS		:= $(PLATFORM_LINK_FLAGS) -Wl,-z,nocopyreloc
PLATFORM_LINK_FLAGS		:= $(PLATFORM_LINK_FLAGS) -Wl,--no-undefined
PLATFORM_LINK_FLAGS		:= $(PLATFORM_LINK_FLAGS) -Wl,-z,noexecstack
PLATFORM_LINK_FLAGS		:= $(PLATFORM_LINK_FLAGS) -L$(PLATFORM_LIBRARY_DIRECTORYS)

PLATFORM_BEGIN_OBJECTS		:= $(PLATFORM_LIBRARY_DIRECTORYS)/crtbegin_dynamic.o
PLATFORM_END_OBJECTS		:= $(PLATFORM_LIBRARY_DIRECTORYS)/crtend_android.o

PROJECT_DEPEND_LIBRARYS		:= $(PROJECT_DEPEND_LIBRARYS) stdc++ c m gcc gcc_eh
